### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by weepy** [adamstark/AudioFile#10]
Would you consider releasing this project under MIT or similar ?

**Comment by adamstark** [comment]
Not at the moment, but I will considering it. If you have a use-case that requires MIT I'm certainly open to hearing it :)

**Comment by weepy** [comment]
I have an iOS app that needs wav file support. Don’t want to oss it for
obvious reasons :-)
Don’t worry if it’s a hassle I’m sure other wave file libs out there.

**Comment by johanneskares** [comment]
Hi @adamstark,

great library! Just wanted to check this old thread if you are still considering changing to MIT? It's not possible to use this library in any closed-source application since GPL infects the whole project.

Johannes

**Comment by mempler** [comment]
Hi,

How about using LGPL v2.1 instead of GPLv3 ? it allows you to keep the project open source (and must still be open source if modified) however you can still link against it as long as it's dynamically linked and can be quite literally replaced via a copy-paste

I've linked here an TL;DR on what it does:
https://tldrlegal.com/license/gnu-lesser-general-public-license-v2.1-(lgpl-2.1)

**Comment by weepy** [comment]
I think actually that's also the case with GPLv3 (you can link against if
the source isn't changeD).

**Comment by adamstark** [comment]
Hi all, I have been re-considering my use of GPLv3 for a while now. This library would be top of my list for giving a more permissive licence. I'm not totally sure how it works with changing a library licence when people have already contributed to it. By default their contributions are provided under the licence of the repository, so I think i need to confirm with them first...

@mynameisjohn 
@Sidelobe 
@MatthieuHernandez 
@Abhinav1997 
@helloimmatt 
@BenjaminHinchliff 
@emiro85

Do you approve of moving this repository (AudioFile) and therefore your contributions to a MIT licence?

Thanks,
Adam

**Comment by adamstark** [comment]
If I could ask you each to comment here rather than just adding a reaction so it is a bit clearer that would be great :)

**Comment by abhinav-jhanwar** [comment]
I’m fine with it.

**Comment by BenjaminHinchliff** [comment]
I'm good with whatever you decide - thank you for the great work

**Comment by emiro85** [comment]
Fine for me as well.

**Comment by Sidelobe** [comment]
Absolutely fine with me switching over to MIT license 👌

**Comment by mynameisjohn** [comment]
Fine with me too - thanks for checking.

**Comment by helloimmatt** [comment]
All good go for it. Thanks for checking with me as well :)

**Comment by adamstark** [comment]
@MatthieuHernandez - any thoughts? :)

**Comment by MatthieuHernandez** [comment]
I'm still wondering what I'm doing here 😆 but yes I totally agree with that. Sorry for my late reply.

**Comment by adamstark** [comment]
Thanks @MatthieuHernandez - you are listed in the collaborator list for the repo. I wasn't totally sure how as I didn't see a commit but assumed it was a contribution somewhere or a contribution to a contribution? Either way, thanks for confirming!

Thanks to everyone else for confirming too - I'll get to this in the next few days 

Adam

**Comment by MatthieuHernandez** [comment]
@adamstark I just checked and it turns out I reviewed and approved a pull request 2 years ago.

**Comment by adamstark** [comment]
Yes, that sounds right - I knew it was something like that :) Thank you!

**Comment by adamstark** [comment]
It's done! AudioFile is now licensed under the MIT licence :)

Thanks all.

**Comment by adamstark** [comment]
If anyone is interested, I wrote a little about my thinking behind doing this (as well as lots of people asking me to, of course): https://twitter.com/mostlynoise/status/1482417156033814532
