### ISSUE TITLE
Request: add support for wave files with 32-bit samples

### ISSUE THREAD

**Issue by Sidelobe** [adamstark/AudioFile#11]
Currently, 8, 16 and 24 are supported.
I know 32 is less common, but it's probably very little effort to add.

**Comment by adamstark** [comment]
Yes, a very good suggestion! I'll do that once I next find a bit of time to work on the library :)

**Comment by Sidelobe** [comment]
I've made a couple of modifications and have 32 bit wave file reading and writing working  (added corresponding unit tests and test data)

I'd be happy to push to a feature branch so I can create a pull request for you to review 😃

**Comment by adamstark** [comment]
Sure, if you want to do a pull request I can take a look! And thanks! :)
