### ISSUE TITLE
Unresolved external symbol

### ISSUE THREAD

**Issue by Kaaserne** [adamstark/AudioFile#12]
Error	LNK2019	unresolved external symbol "public: __thiscall AudioFile<double>::AudioFile<double>(void)" (??0?$AudioFile@N@@QAE@XZ) referenced in function _main	Project1	

When trying to create object AudioFile<double>. Does this have to do something with templates being declarated in cpp files, instead of the .h file?

**Comment by adamstark** [comment]
This sounds a little like AudioFile.cpp is not included in your project (or otherwise not included in the files to compile). Is that the case?

The template implementation can be declared in the .cpp file and it shouldn't be a problem as long as you include the .cpp file itself. :)
