### ISSUE TITLE
Issue in Unit Tests - All files are written as wave, none as aiff

### ISSUE THREAD

**Issue by Sidelobe** [adamstark/AudioFile#14]
In`FileWritingTests.cpp`, the `format` parameter is missing in the `save()` calls. Therefore, the default parameter is used for both, which means wave files are written regardless of the format.

**Comment by mithusingh32** [comment]
Good catch

Should be a simple fix: 

```
if (format == AudioFileFormat::Wave)
    {
        return audioFile.save ("audio-write-tests/" + numChannelsAsString + "_" + sampleRateAsString + "_" + bitDepthAsString + "bit" + ".wav", format);
    }
    
    else if (format == AudioFileFormat::Aiff)
    {
        return audioFile.save ("audio-write-tests/" + numChannelsAsString + "_" + sampleRateAsString + "_" + bitDepthAsString + "bit" + ".aif", format);
    }
```

**Comment by adamstark** [comment]
Hi guys,

Thank you for your thoughts and your time. I have fixed this in a commit just now to the develop branch:

https://github.com/adamstark/AudioFile/commit/83797d3750741ee16813df4189e70dbe5f7d2f25

Thanks,

Adam
