### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by jean-barre** [adamstark/AudioFile#15]
I do not know if this is fixed by the XCode environment but I had issues running the FileWritingTests on Linux:

- the filepath of created files is not relative 
 I had to edit lines 39 and 44 to `return audioFile.save ("./audio-write-tests/...`
- the repertory **audio-write-tests** does not exist.
 I had to create it.

Again this may be due to the environment. Great work

**Comment by adamstark** [comment]
Thanks! I've now fixed this on the develop branch
