### ISSUE TITLE
Out-of-bounds Read  Vuln

### ISSUE THREAD

**Issue by octopus-666** [adamstark/AudioFile#16]
A wav file with large dataChunkSize can make program crash.
[s.zip](https://github.com/adamstark/AudioFile/files/2962691/s.zip)
http://cwe.mitre.org/data/definitions/125.html

**Comment by adamstark** [comment]
Thanks for letting me know - I will try to take a look at this soon :)

**Comment by adamstark** [comment]
Sorry it took me forever to look at this - I've just pushed a fix that catches this situation gracefully with an error to the develop branch,

Adam
