### ISSUE TITLE
getAiffSampleRate  returns unsigned value. So you can't use -1 to compare.

### ISSUE THREAD

**Issue by soundpoint** [adamstark/AudioFile#19]
sampleRate = getAiffSampleRate (fileData, p + 16);
    
    // check the sample rate was properly decoded
    if (sampleRate == -1)
    {
        std::cout << "ERROR: this AIFF file has an unsupported sample rate" << std::endl;
        return false;

**Comment by adamstark** [comment]
I've fixed this now :)
