### ISSUE TITLE
Support for higher bitrates?

### ISSUE THREAD

**Issue by clone45** [adamstark/AudioFile#29]
Hello!

I recently replaced dr_wav with your wonderful AudioFile library.  I've been getting reports from some of my users that .wav files that previously loaded and play fine no longer work.  I've found that the reason is that the .wav files that they were using were greater than than 24-bit.  

The bitrates supported by dr_wav are:

Unsigned 8-bit PCM
Signed 12-bit PCM
Signed 16-bit PCM
Signed 24-bit PCM
Signed 32-bit PCM
IEEE 32-bit floating point
IEEE 64-bit floating point

Would it be possible to support these .wav file formats?

Thanks!
Bret

**Comment by adamstark** [comment]
Hi Bret, 

Thanks for getting in touch and I'm glad you have found AudioFile useful. I have added 32-bit support on the current develop branch. Perhaps that will solve some of your issues? I can look at extending the sample types further still also,

Thanks,

Adam

**Comment by clone45** [comment]
I'm sure that will suffice!  I have another reported issue.  The same user has sent me a .wav file recorded at 48000 Hz instead of 44100 Hz that won't load.  Would that happen to also be fixed on the development branch?

**Comment by adamstark** [comment]
Is there any chance you could share the audio file with me so I could try and debug why that is happening?

Thanks,
Adam

**Comment by bret-2600** [comment]
You bet!  Here is it: https://drive.google.com/file/d/15-Gsr6Rhn4AUyUKCO9_WmpmkG2rLGq-5/view?usp=sharing

**Comment by adamstark** [comment]
Try the latest push to develop - this audio file is in 'extensible' format and I was not allowing those to be opened. Have changed that now (though I wonder if that might get me into different trouble later on haha).

**Comment by clone45** [comment]
Sure! I can git it a shot! I'll try it right now and report back.

**Comment by clone45** [comment]
Yep, it's working great! 🥇 Thank you!!

**Comment by adamstark** [comment]
Awesome! Glad to hear that :)
