### ISSUE TITLE
Make AudioFile.h compatible with more compilation options.

### ISSUE THREAD

**Issue by MatthieuHernandez** [adamstark/AudioFile#34]
Make AudioFile.h compatible with `-Wall` `-Wextra` ` -pedantic` `-Werror`  compilation options for GCC (And `/W4` and `/WX` for MSVC).
This will make it easier project compatible with many projects.
You can use GitHub Actions to easly run tests on Linux, Windows and Mac.

**Comment by MatthieuHernandez** [comment]
I have this `error :  there are no arguments to ‘memcmp’ that depend on a template parameter, so a declaration of ‘memcmp’ must be available [-fpermissive]`

**Comment by adamstark** [comment]
I am in the process of moving AudioFile to a CMake system with GitHub Actions testing. Once I've done that then it'd be a good time to look at the various compiler options to see if we can make it better for different platforms :)

**Comment by MatthieuHernandez** [comment]
Perfect thank you. 👍
