### ISSUE TITLE
Can I get the Header size?

### ISSUE THREAD

**Issue by mahuichao** [adamstark/AudioFile#41]
Hello , this is a good tool.If I want to get the header size of a wav file ,maybe 44 bytes or else , can this tool help me?

**Comment by adamstark** [comment]
Hi - do you mean before or after the audio file has been loaded into memory?

**Comment by mahuichao** [comment]
I mean before the audio file has been loaded into memory ,the original wav header size.

**Comment by adamstark** [comment]
So not yet, but it would be a nice feature. I can look into adding this at some point...

**Comment by mahuichao** [comment]
OK thanks
