### ISSUE TITLE
Please make this features

### ISSUE THREAD

**Issue by xverizex** [adamstark/AudioFile#47]
Need that might be got 'unsigned char *data' for reading raw data.

**Comment by adamstark** [comment]
Hi there, the library parses the audio file and keeps the samples and then stores metadata (e.g. bit depth) about the audio in specific variables. So it doesn't keep the raw data in memory for us to return a pointer to it.

We could have a pointer to the audio data, but even that is structured differently to the audio file byte structure. I think you might be better just loading the file into memory if you need the raw bytes?
