### ISSUE TITLE
Problem with max() function under Windows

### ISSUE THREAD

**Issue by codeworrier** [adamstark/AudioFile#48]
There are several locations where the codebase uses the max() function, such as this one

                int32_t sampleAsInt = (int32_t) (samples[channel][i] * std::numeric_limits<int32_t>::max());

the problem, as documented here [ https://stackoverflow.com/questions/27442885/syntax-error-with-stdnumeric-limitsmax ] is that Windows defines max() and min() macro's, which don't expand nicely and aren't what we want.  The solution is one suggested, to disable macro expansion by doing this

                int32_t sampleAsInt = (int32_t) (samples[channel][i] * (std::numeric_limits<int32_t>::max)());

... which once done in the various places that min() and max() are called fix the issue ...

**Comment by adamstark** [comment]
I've just pushed something to `develop` - does this fix your issue?

Thanks,
Adam
