### ISSUE TITLE
Missing #include <limits>

### ISSUE THREAD

**Issue by dfleury2** [adamstark/AudioFile#49]
gcc 11 complains about numeric_limits not available.

#include <limits> is missing.

Regards,

**Comment by aparks5** [comment]
are you on windows? i had to do this to get build with `AudioFile.h`:
```
#undef max 
#undef min
#include <limits>
```
as even the following did not resolve issues with limits:
```
#define NOMINMAX
#include <windows.h>
#include <limits>
```

**Comment by dfleury2** [comment]
No, under Linux Debian.

**Comment by adamstark** [comment]
I've just pushed something to the `develop` branch - can you let me know if this fixes the problem for you? :)

**Comment by dfleury2** [comment]
Works for me.
Thanks.
