### ISSUE TITLE
Normalize after loading wav file

### ISSUE THREAD

**Issue by Ignasinou** [adamstark/AudioFile#50]
Hey! Thanks for the lib, it really helps! 

A question/feature, more than an issue. I was wondering if you are normalizing the .wav input after loading the file and if this can be disabled somehow.

Best

**Comment by adamstark** [comment]
Hey, thanks for your message. I don't think I am normalising it. I don't recall putting that into the codebase and it feels like it goes against the spirit of what I was trying to do which is just to give a quick and easy way to load an audio file "as-is". Are you finding things seem normalised?
