### ISSUE TITLE
Warnings of "warning: dereferencing type-punned pointer will break strict-aliasing rules"

### ISSUE THREAD

**Issue by clone45** [adamstark/AudioFile#52]
I'd love for these to get addressed!  Much appreciated!

src/Common/AudioFile.h: In instantiation of 'bool AudioFile<T>::decodeWaveFile(std::vector<unsigned char>&) [with T = float]':
src/Common/AudioFile.h:460:16:   required from 'bool AudioFile<T>::load(std::string) [with T = float; std::string = std::__cxx11::basic_string<char>]'
src/Common/sample.hpp:75:29:   required from here
src/Common/AudioFile.h:585:59: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  585 |                     sample = (T)reinterpret_cast<float&> (sampleAsInt);

**Comment by adamstark** [comment]
This should now be addressed on the develop branch

**Comment by clone45** [comment]
Awesome, thank you!
