### ISSUE TITLE
conversion from 48.0 kHz to 44.1 kHz sample rate conversion

### ISSUE THREAD

**Issue by stubbulon5** [adamstark/AudioFile#54]
Hi there,

Thanks so much for this brilliant library. I'm using it with great success so far. I know next to nothing about this stuff which speaks to how simple to use this library is.

I was wondering if you might have some pointers for me, I'm trying to convert a file's sample rate from 48.0 kHz to 44.1 kHz

When I load a file 48.0 kHz, use a.setSampleRate(44100); and then save the file.  
If I play back the file, it sounds slower and lower pitched.

Would you consider adding this scenario to your examples section>?

**Comment by adamstark** [comment]
Hi there, so this library doesn't (currently) do any sample rate conversion. When you set the sample rate you are just setting the metadata in the file for how it should be interpreted by an audio editor. I've considered adding sample rate conversion but it is important to get right and whole libraries exist for this purpose. The main goal of this library was to be a nice interface for loading audio files and accessing their audio samples and then re-saving them again.

So yes, for now, you'd have to use one of the other resampling libraries but if I can find some time I'll think about adding some re-sampling! 

Adam
