### ISSUE TITLE
Can't compile AudioFile with Clang14.0.6

### ISSUE THREAD

**Issue by Yhcrown** [adamstark/AudioFile#62]
Hi adam:
Recently I want to use fuzz to test this program, but it can't be compiled correctly in my enviroment (Ubuntu 22.04, clang version 14.0.6). The error message is here:
```
In file included from /workspace/AudioFile/tests/main.cpp:3:
/workspace/AudioFile/tests/doctest/doctest.h:4032:33: error: variable length array declaration not allowed at file scope
        static char             altStackMem[4 * SIGSTKSZ];
                                ^           ~~~~~~~~~~~~
1 error generated.
gmake[2]: *** [tests/CMakeFiles/Tests.dir/build.make:76: tests/CMakeFiles/Tests.dir/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:142: tests/CMakeFiles/Tests.dir/all] Error 2
gmake: *** [Makefile:101: all] Error 2
```
according to https://github.com/adishavit/argh/issues/66
This issue seems to be related to doctest. I guess we need to upgrade the doctest version to 2.46. If you don't mind, I'll propose a PR on this issue.
Thanks & Best regards!

**Comment by adamstark** [comment]
This is now merged in :)
