### ISSUE TITLE
Only one hpp file

### ISSUE THREAD

**Issue by xavier7179** [adamstark/AudioFile#7]
Due to the fact that you're implementing a Template, to avoid issues with different compilers, you should consider having only one .hpp file with the full template definition there.

**Comment by adamstark** [comment]
Hi there,

Thanks for getting in touch. Yes, I have been considering this. The downside is that one would lose the simplicity and readability of the header file at present. I am giving it some thought. :)

Could you talk me through the issues with different compilers? I know that there are issues around having to explicitly itemise types, i.e. I have added in the .cpp file...

```
template class AudioFile<float>;
template class AudioFile<double>;
```

but for this class, those are probably the only two types one would use with the library (and it wouldn't be hard to add another if need be) I don't see it as a huge issue here. I'd be interested in the compiler issues you mentioned.

Let me know your thoughts,

Best,

Adam

**Comment by xavier7179** [comment]
Hello.

I found that on OSX (current 10.13.x version) it is not working unless you
put everything on a .hpp file, because the clang compiler is not going to
be able to produce the code and the linker fails due to the missing of
implementations. I know that the downside of losing the simplicity can
bother you (in fact, all my students will go for the same reason! ;) ), but
portability will be a good way of spreading the usage of your library!

Regarding the template ability, if you’d like I’m happy to open a different
issue but when I needed a int16_t template, I patched up some internal
function to make it work properly.

Best,
Alessandro

From: Adam Stark <notifications@github.com> <notifications@github.com>
Reply: adamstark/AudioFile
<reply@reply.github.com>
<reply@reply.github.com>
Date: 24 September 2018 at 20:25:07
To: adamstark/AudioFile <audiofile@noreply.github.com>
<audiofile@noreply.github.com>
Cc: xavier7179 <notinmyhead@gmail.com> <notinmyhead@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [adamstark/AudioFile] Only one hpp file (#7)

Hi there,

Thanks for getting in touch. Yes, I have been considering this. The
downside is that one would lose the simplicity and readability of the
header file at present. I am giving it some thought. :)

Could you talk me through the issues with different compilers? I know that
there are issues around having to explicitly itemise types, i.e. I have
added in the .cpp file...

template class AudioFile<float>;
template class AudioFile<double>;

but for this class, those are probably the only two types one would use
with the library (and it wouldn't be hard to add another if need be) I
don't see it as a huge issue here. I'd be interested in the compiler issues
you mentioned.

Let me know your thoughts,

Best,

Adam

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/adamstark/AudioFile/issues/7#issuecomment-424076013>,
or mute the thread

**Comment by jagger2048** [comment]
Well, I use this library through  `#include <AudioFile.cpp>`  instead of `#include <AudioFile.h>`  , avoiding MSVC's compiler missing  the define of the template class.  If you don't want to combine the .cpp and .h file as a .hpp file, maybe it is an alternative.

**Comment by adamstark** [comment]
The library is now a header-only library. Would be great to hear your feedback and I hope it is easier for you to use now :)
