### ISSUE TITLE
Does not compile out of the box on Ubuntu 22.04 - doctest.h needs to be upgraded to 2.4.10

### ISSUE THREAD

**Issue by Whips66** [adamstark/AudioFile#74]
When I try and compile it get an error in doctest.h 

cmake --build .
[ 25%] Built target Examples
Consolidate compiler generated dependencies of target Tests
[ 37%] Building CXX object tests/CMakeFiles/Tests.dir/main.cpp.o
In file included from /home/paulw/AudioFile/tests/main.cpp:3:
/home/paulw/AudioFile/tests/doctest/doctest.h:4032:47: error: size of array ‘altStackMem’ is not an integral constant-expression
 4032 |         static char             altStackMem[4 * SIGSTKSZ];
      |                                               ^
gmake[2]: *** [tests/CMakeFiles/Tests.dir/build.make:76: tests/CMakeFiles/Tests.dir/main.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:142: tests/CMakeFiles/Tests.dir/all] Error 2
gmake: *** [Makefile:101: all] Error 2

This is because there is a problem with the doctest.h file, upgrading doctest.h to the latest version 2.4.10 solves the problem and it builds okay. 

 cmake --build .
[ 12%] Building CXX object examples/CMakeFiles/Examples.dir/examples.cpp.o
[ 25%] Linking CXX executable Examples
[ 25%] Built target Examples
[ 37%] Building CXX object tests/CMakeFiles/Tests.dir/main.cpp.o
[ 50%] Building CXX object tests/CMakeFiles/Tests.dir/GeneralTests.cpp.o
[ 62%] Building CXX object tests/CMakeFiles/Tests.dir/WavLoadingTests.cpp.o
[ 75%] Building CXX object tests/CMakeFiles/Tests.dir/AiffLoadingTests.cpp.o
[ 87%] Building CXX object tests/CMakeFiles/Tests.dir/FileWritingTests.cpp.o
[100%] Linking CXX executable Tests
[100%] Built target Tests

**Comment by adamstark** [comment]
This is now updated on the `develop` branch :)
