### ISSUE TITLE
Bug report: When the audio file is empty, the following line will result in an out-of-bounds access

### ISSUE THREAD

**Issue by niucheney** [adamstark/AudioFile#78]
https://github.com/adamstark/AudioFile/blob/bcb61a47e64fe4e7fc3d8a8664b8a23a192bddb7/AudioFile.h#L1249

**Comment by adamstark** [comment]
Thank you - I've pushed a fix for this here...

https://github.com/adamstark/AudioFile/commit/f46a4e497b551b97d5c4a214e3b62b477edd4022
