### ISSUE TITLE
 Example Fucntion "loadAudioFileAndProcessSamples" Returning Corrupted File

### ISSUE THREAD

**Issue by DDixon0** [adamstark/AudioFile#87]
Hi Adam,

In your examples.cpp file, the "loadAudioFileAndProcessSamples" function, on line 144, the audio file is incorrectly saved as an Aiff rather than a Wave file. This results in a corrupted audio file output. 

Thank You for this library and the provided examples. Very helpful for new programmers.

**Comment by adamstark** [comment]
Thank you! I've fixed this now on develop
