### ISSUE TITLE
float samples read in with wrong value

### ISSUE THREAD

**Issue by ooostbooo** [adamstark/AudioFile#90]
for my test cases i read in an 48 kHz 16 bit sample consisting of all values being exactly 0.5 ( i can provide the file at your convenience)

in 1.1.0 the values read into an AudioFile<float> are exactly 0.5 (which i would expect since 0.5 is representable in 32bit float)

in 1.1.1 they are 0.500015259

**Comment by adamstark** [comment]
So, this is a small floating point rounding error. I did spent a long time thinking about this and I have written up some explanation on the README page (read the section "A Note On Types").

Basically, a 16-bit sample is stored internally as an integer in the range [-32767, 32767].

What this means is that your 0.5 is 32767 * 0.5 = 16383.5

That can't be represented in integer form (needed when we write to files) so it gets rounded to 16384, which gives...

16384 / 32767 = 0.5000152593.

So this is the intended behaviour of the library.

You might think, but why don't we do the full 16-bit range... [-32767, 32768]. Then we can do:

32768 * 0.5 = 16384 

i.e. an integer, which we can store. But, then you will notice that the negative range has less resolution (32767) than the positive range (32768), and so they are not symmetric. And then as well as the asymmetry you'd have the problem you had with -0.5 anyway...

So better to have a symmetric representation and accept some small rounding errors for some values (other values also have rounding errors in the 32768 version, they're just not as 'round' as 0.5).

Hope this makes sense and thanks for using the library :)

**Comment by adamstark** [comment]
I actually got this upside down - the full 16-bit range would be [-32768, 32767], so you would have this problem with 0.5 regardless of the approach used there. 

Short version: it's a rounding thing! :)
