### ISSUE TITLE
cstdint

### ISSUE THREAD

**Issue by johnallsup** [adamstark/AudioFile#91]
The `AudioFile.h` uses e.g. `uint8_t`. For this we need to include `cstdint`, but this include is missing. (At least, this was my experience using g++ 13.2.0 under Kubuntu 24.04).

Inserting `#include <cstdint>` removes the issue.

Example error:
```
/usr/local/include/AudioFile.h:1504:1: error: ‘uint8_t’ does not name a type
 1504 | uint8_t AudioSampleConverter<T>::sampleToUnsignedByte (T sample)
      | ^~~~~~~
```

**Comment by adamstark** [comment]
This is now done on the develop branch :)
