### ISSUE TITLE
MP3 support?

### ISSUE THREAD

**Issue by godofecht** [adamstark/AudioFile#92]
Just out of curiosity, is there any effort to add the ability to read and write MP3 files?

**Comment by adamstark** [comment]
That would be awesome - but for a few reasons I don't think I'll get to that for a while. Firstly, I want to keep this as a very lightweight header file library for audio files, and doing an MP3 encoder / decoder is much more complicated than the WAV / AIFF files the library currently handles. The second reason is I'm not clear on what the licensing issues are with MP3 and would need to look into that to see if it's ok for me to publish an open source encoder / decoder...
